#ddev-generated
services:
  mindsdb:
    container_name: ddev-${DDEV_SITENAME}-mindsdb
    hostname: ddev-${DDEV_SITENAME}-mindsdb
    image: "mindsdb/mindsdb:${MINDSDB_DOCKER_TAG:-lightwood}"
    restart: "no"

    environment:
      PYTHONWARNINGS: "ignore::DeprecationWarning,ignore::UserWarning:langchain:34,ignore::UserWarning:torchvision.io.image:13"
      VIRTUAL_HOST: ${DDEV_HOSTNAME}
      HTTP_EXPOSE: "47334"
      MINDSDB_DEBUG: "1"
      PYTHONUNBUFFERED: "1"
      MINDSDB_APIS: "http,mysql"

    entrypoint: 'python'
    command: '-Im mindsdb --config=/root/mindsdb_config.json'

    expose:
      - "47334" # HTTP API
      - "47335" # MySQL

    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
      com.ddev.platform: ddev

    volumes:
      - type: "volume"
        source: mindsdb
        target: "/root/mdb_storage"
        volume:
          nocopy: true
      - ".:/mnt/ddev_config"
      - "./mindsdb_config.json:/root/mindsdb_config.json"
      - "ddev-global-cache:/mnt/ddev-global-cache"

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:47334/api/util/ping')"]
      start_period: 90s
      start_interval: 10s
      interval: 60s
      timeout: 10s
      retries: 5

volumes:
  mindsdb:
